[package]
name = "tree-sitter-lilypond"
description = "LilyPond-embedded Scheme grammar for the tree-sitter parsing library"
version = "0.0.1"
authors = ["Nathan Whetsell <nathan.whetsell@gmail.com>"]
keywords = ["incremental", "parsing", "lilypond", "scheme"]
categories = ["parsing", "text-editors"]
repository = "https://github.com/nwhetsell/tree-sitter-lilypond-scheme"
edition = "2018"
license = "MIT"

build = "bindings/rust/build.rs"
include = [
  "bindings/rust/*",
  "grammar.js",
  "queries/*",
  "src/*",
]

[lib]
path = "bindings/rust/lib.rs"

[dependencies]
tree-sitter = "~0.20.3"

[build-dependencies]
cc = "1.0"
